### ISSUE TITLE
Why do you need loops in testing?

### ISSUE THREAD

**Issue by ys-dpc** [cypw/PyTorch-MFNet#18]
Hi ! my friend
Your code is well written.I'm a novice in behavioral recognition.
I want to ask why 'for i_round in range(total_round):' is set in the test.py file.
Isn't it enough to test once?
Although I don't understand why, I tested it with this loop.
I found that the final accuracy was affected by the number of cycles.
This makes me even more confused, for a fixed  weight, how can the final accuracy be different?
Is it influenced by 'duplication = 0.92 * duplication + 0.08 * avg_score[video_subpath_i][3]'?
I'm ashamed to say that I didn't understand this line of code.

**Comment by cypw** [comment]
Hi @ys-dpc ,

That testing script randomly crops each video multiple times and get the final video level prediction using an averaged score. It uses a "for loop" to pass the eval/test set multiple times for this purpose. Check this #16 #17 for more info about why we need multi-crop testing.

Since random crop is adopted, the final accuracy can be different at each run. But, the accuracy is actually very stable if the total number of round is sufficiently large, e.g. total_round=40. Check issue #4 for the testing log.
*You can also try to do center crop and sample clip from the middle of the video for stable result. This can be easily done by changing the sampler and enable CenterCrop.

`duplication` is just an indicator (i.e. counter) showing averaged number of crops used for each video (see: L174, L180). Here, I use running mean to get the estimated mean value. Please feel free to remove this indicator, since it does not affect the final accuracy.

*btw, `total_round ` is recommended to set to around 50 for highest results as discussed in #4 . But, as the testing log shows, the accuracy becomes saturated after the first several loops. So, you can also set it to smaller values depends on your patient.

Thanks for trying our code.

**Comment by ys-dpc** [comment]
Thank you very much for your reply, my friend. I understand what you mean. Happy weekend! Please forgive me for my late reply because I went out to see a movie with my friends this weekend.

I was wondering if you could make some improvements based on your work, such as using slowfast networks or using the attention model

I think it's great that you can just use the original video instead of first processing it into a picture to do a 3D convolution, but other traditional ways of representing motion information such as optical flow cannot be obtained directly from the original video.

So, if we can find a new efficient and concise way to represent motion information, we can greatly improve the accuracy of behavior recognition. I don't know if you have any ideas about this
